//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjektCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawa
    {
        public int id_dostawa { get; set; }
        public int id_klient { get; set; }
        public int id_adres_dostawy { get; set; }
        public int id_zamowienie { get; set; }
        public Nullable<System.DateTime> data_dostawy { get; set; }
    
        public virtual Adre Adre { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
