//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjektCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Zamowienies = new HashSet<Zamowienie>();
        }
    
        public int id_pracownik { get; set; }
        public int id_kontakt { get; set; }
        public int id_adres { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public System.DateTime data_uro { get; set; }
        public System.DateTime data_zatr { get; set; }
    
        public virtual Adre Adre { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienies { get; set; }
    }
}
